services:
  app:
    image: organization:1.0
    volumes:
      - ./:/projects/organization
      - upload:/projects/organization/organization/templates/File/upload  #文件上传目录
      - Works_upload:/projects/organization/organization/templates/Works/upload  #作品上传目录
    ports:
      - "80:80"  # 假设容器内服务监听80端口
    restart: unless-stopped  # 推荐：容器崩溃时自动重启

# 定义命名卷
volumes:
  upload:
  Works_upload: